<?php

namespace App\Command;

use App\Service\ImportService;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportMissingCommand extends BaseCommand
{
    public static $defaultName = 'mk:import:missing';

    protected ImportService $importService;

    protected LoggerInterface $logger;

    public function __construct(
        EntityManagerInterface $em,
        ImportService $importService,
        LoggerInterface $logger
    )
    {
        parent::__construct($em);

        $this->logger = $logger;
        $this->importService = $importService;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        parent::execute($input, $output);

        $missingIssues = $this->importService->getMissingImportIssues('one-piece');

        return 0;
    }
}