version: '3'
services:
  web:
    build:
      context: ./docker
      dockerfile: web.Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/pulsar
    depends_on:
      - mariadb

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8888:80'
    volumes:
      - .:/var/www/pulsar
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - mariadb

  mariadb:
    image: mariadb:10.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Lyk4w0lf13Mysql
      MYSQL_DATABASE: pulsar_manga
      MYSQL_USER: lykaos
      MYSQL_PASSWORD: Lyk4w0lf13Mysql
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql