easy_admin:
  design:
    menu:
      - label: 'Manga'
        icon: 'book'
        children:
          - { entity: 'Manga', icon: 'book', label: 'Mangas' }
          - { entity: 'MangaPlatform', icon: 'book', label: 'Manga Platforms' }
          - { entity: 'Chapter', label: 'Chapters' }
          - { entity: 'Platform', label: 'Platforms' }
      - label: 'Jobs'
        icon: 'wrench'
        children:
          - { entity: 'Cron', icon: 'wrench', label: 'JMose Jobs' }
