easy_admin:
  design:
    menu:
      - label: 'Manga'
        icon: 'book'
        children:
          - { entity: 'Manga', label: 'Mangas', icon: 'book', default: true }
          - { entity: 'MangaPlatform', label: 'Manga Platforms', icon: 'book' }
          - { entity: 'Chapter', label: 'Chapters', icon: 'book-open' }
          - { entity: 'Platform', label: 'Platforms', icon: 'server' }
      - label: 'Jobs'
        icon: 'wrench'
        children:
          - { entity: 'Cron', icon: 'wrench', label: 'JMose Jobs' }
          - { entity: 'Job', icon: 'wrench', label: 'JMS Jobs' }
