easy_admin:
  entities:
    Job:
      class: JMS\JobQueueBundle\Entity\Job
      list:
        fields:
          - id
          - command
          - args
          - state
          - output
          - errorOutput
        actions: ['-new']
      form:
        fields:
          - id
          - command
          - args
          - state
          - output
          - errorOutput
