easy_admin:
  entities:
    Manga:
      class: App\Entity\Manga
      list:
        fields:
          - id
          - title
          - altTitles
          - status
          - { property: 'image.url', type: 'image' }
          - createdAt
          - platforms
      form:
        fields:
          - id
          - title
          - status
          - createdAt
