easy_admin:
  entities:
    Manga:
      class: App\Entity\Manga
      list:
        fields:
          - id
          - title
          - status
          - createdAt
          - platforms
          - userMangas
