easy_admin:
  entities:
    MangaPlatform:
      class: App\Entity\MangaPlatform
#      templates:
#        list: 'admin/MangaPlatform/list.html.twig'
      list:
        actions: ['import']
        fields:
          - id
          - { property: 'manga.title', label: 'Title' }
          - { property: 'platform.name', label: 'Platform' }
          - autoUpdate
          - description
          - viewsCount
          - { property: sourceUrl, type: url }
          - updatedAt
          - chapters
      form:
        fields:
          - id
          - description
          - autoUpdate
          - author
          - viewsCount
          - sourceUrl
