easy_admin:
  entities:
    Platform:
      class: App\Entity\Platform
      list:
        fields:
          - id
          - name
          - language
          - baseUrl
          - mangaPath
          - chapterPath
