#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#fos_oauth_server_token:
#  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

#fos_oauth_server_authorize:
#  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
# api/config/routes.yaml
authentication_token:
  path: /authentication_token
  methods: ['POST']

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh