App\Entity\User:
  collectionOperations:
    me:
      pagination_enabled: false
      path: '/me'
      method: GET
      controller: App\Controller\MeController
      read: false
      security: 'is_granted("ROLE_USER")'
  itemOperations:
    get:
      openapi_context:
        summary: 'hidden'
      read: false
      output: false
  attributes:
    normalization_context:
      groups: ["read:User"]